### ISSUE TITLE
How is .exe running on macOS ?

### ISSUE THREAD

**Issue by harsh-vardhhan** [esy-ocaml/hello-reason#9]
Apologies if its a dumb question but how is `Hello.exe` build by esy in `./_build/default/bin/Hello.exe` able to run on macOS since its a windows specific format ?

**Comment by andreypopp** [comment]
Not a dumb question! This is not a windows specific file, this is a macOS
executable but with .exe extension which is standard for windows
executables. On macOS (and Linux) there’s no need in a specific extension
for executables and .exe is allowed too (though it is less common). In this
specific case the executable is produced by dune build system, I don’t know
the exact motivation behind this but I think it was done due to consistency
reasons (dune works on windows too along with esy and this starter project).
